# This is a basic workflow to help you get started with Actions

name: Mirror Site

# Controls when the workflow will run
on:
  schedule:
    - cron: '11 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Restore the file attrs
        continue-on-error: true
        run:  .github/bin/save-file-attrs.py restore

      # Runs a single command using the runners shell
      - name: Download the files
        run:  wget -m --no-host-directories https://chriskthomas.com

      - name: Save the file attrs
        run:  .github/bin/save-file-attrs.py save

      - name: List files
        run:  ls -al

      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -- . ':!.github'
          git commit -m "automatically update site"

      - name: Push changes
        run:  git push
